version: 0.2

phases:
  install:
    commands:
      - pip install -r ./cdk-app/requirements.txt
      - npm install -g aws-cdk
  build:
    commands:
      - cd ./cdk-app
      - cdk bootstrap aws://141262319565/us-east-1
      - cdk synth
      - cdk deploy --require-approval never
